server:
  port: "8089"
  mode: "debug"

database:
  host: "localhost"
  port: 5440
  user: "admin"
  password: "vokzal_secret_2026"
  dbname: "vokzal"
  sslmode: "disable"

nats:
  url: "nats://localhost:4222"
  user: "vokzal"
  password: "nats_secret_2026"

logger:
  level: "debug"

minio:
  endpoint: "localhost:9000"
  access_key: "vokzal"
  secret_key: "minio_secret_2026"
  bucket: "vokzal-documents"
  use_ssl: false
