server:
  port: "8087"
  mode: "debug"

database:
  host: "localhost"
  port: 5432
  user: "admin"
  password: "vokzal_secret_2026"
  dbname: "vokzal"
  sslmode: "disable"

nats:
  url: "nats://localhost:4222"
  user: "vokzal"
  password: "nats_secret_2026"

logger:
  level: "debug"

sms:
  api_id: "YOUR_SMS_RU_API_ID"
  url: "https://sms.ru/sms/send"

email:
  smtp_host: "smtp.yandex.ru"
  smtp_port: 587
  username: "noreply@vokzal.tech"
  password: "YOUR_EMAIL_PASSWORD"
  from: "Вокзал.ТЕХ <noreply@vokzal.tech>"

telegram:
  bot_token: "YOUR_BOT_TOKEN"
  webhook_url: "https://api.vokzal.tech/v1/notify/telegram/webhook"

local_agent:
  url: "http://localhost:8081"
